dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('scan', views.scan, name='scan'),
]

extra_user_info/urls.py
from django.urls import path, include
from . import views

app_name = 'signup'

urlpatterns = [
    path('signupWithEmail/', views.signup_with_email, name='signupWithEmail'),
    path('register', views.signup_with_token, name='signupWithToken'),
    path('loginWithEmail/', views.login_with_email, name='loginWithEmail'),
]

securityscan/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.authtoken.views import obtain_auth_token
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.HomeView.as_view(), name="home"),
    path("targets/", views.TargetView.as_view(), name="targets"),
    path("scan/", views.ScanView.as_view(), name="scan"),
    path("pricing/", views.PricingView.as_view(), name="pricing"),
    path("dashboard", views.DashboardView.as_view(), name="dashboard"),
    path("dashboard/", include("dashboard.urls")),
    path("login/", views.LoginView.as_view(), name="login"),
    path("signup/", views.SignupView.as_view(), name="signup"),
    path("user/", include('extra_user_info.urls')),
    path("", include("allauth.urls")),
    path("logout", views.google_logout, name="logout"),
]

dashboard/models.py
from django.db import models

# Create your models here.

extra_user_info/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class UserExtraInfo(AbstractUser):
    signup_url = models.CharField(max_length=255, null=True, blank=True)

dashboard/views.py
from django.http import JsonResponse
import json
import nmap3


def scan(request):
    if (request.method == 'POST'):
        parsed_body = json.loads(request.body)
        target = parsed_body.get('target')
        tags = parsed_body.get('tags')
        label = parsed_body.get('label')

        nm = nmap3.Nmap()
        result = nm.scan_top_ports('upwork.com')
        print('======', result)

        # nm = nmap.PortScanner()
        # nm.scan(target, arguments='-p 1-1000')
        
        # for host in nm.all_hosts():
        #     print('====================================')
        #     print("Host : %s (%s)" % (host, nm[host].hostname()))
        #     print("State : %s" % nm[host].state())
        #     for proto in nm[host].all_protocols():
        #         print('----------')
        #         print("Protocol : %s" % proto)

        #         lport = nm[host][proto].keys()
        #         lport.sort()
        #         for port in lport:
        #             print("Port : %s\tstate : %s" % (port, nm[host][proto][port].state()))
        
        # Get the results
        scan_results = nm.csv().splitlines()
        print('=====', scan_results)
        return JsonResponse({'success': True,'scanResults': scan_results})

extra_user_info/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.core.mail import send_mail
from .models import UserExtraInfo
from rest_framework.authtoken.models import Token
from django.contrib.auth import login
from django.conf import settings
import json
import hashlib
import datetime


def signup_with_email(request):
    if request.method == 'POST':
        parsed_body = json.loads(request.body)
        receiver = parsed_body.get('to')
        # check if user is already exists
        try:
            user = UserExtraInfo.objects.get(email=receiver)
            if user:
                return JsonResponse({'success': False, 'message': 'User already exists'})
        except UserExtraInfo.DoesNotExist:
            # make signup_url
            token = hashlib.sha256(receiver.encode()).hexdigest()
            signup_url = request.get_host() + '/register?token=' + \
                token + '&email=' + receiver
            try:
                # send_mail(
                #     "Welcome " + receiver,
                #     signup_url,
                #     "noreply@example.com",
                #     [receiver],
                #     fail_silently=False,
                # )
                UserExtraInfo.objects.create(email=receiver, signup_url=token)
                return JsonResponse({'success': True})
            except Exception as e:
                return JsonResponse({'success': False, 'message': e})


def signup_with_token(request):
    if request.method == 'GET':
        signup_token = request.GET.get('token')
        user_email = request.GET.get('email')
        return render(request, 'signup.html', {'token': signup_token, 'email': user_email})
    elif request.method == 'POST':
        parsed_body = json.loads(request.body)
        token = parsed_body.get('token')
        email = parsed_body.get('email')
        password = parsed_body.get('password')
        # get user info from database
        try:
            user = UserExtraInfo.objects.get(email=email)
            if user.email:
                # compare token
                if user.signup_url == token:
                    # hash password and save userinfo
                    user.set_password(password)
                    user.last_login = datetime.datetime.now()
                    user.signup_url = None
                    user.save()
                    return JsonResponse({'success': True, 'redirectUrl': 'http://' + request.get_host()+'/'})
                else:
                    return JsonResponse({'success': False, 'message': 'Invalid token'})
        except UserExtraInfo.DoesNotExist:
            return JsonResponse({'success': False, 'message': 'Invalid email'})


def login_with_email(request):
    if request.method == 'POST':
        parsed_body = json.loads(request.body)
        email = parsed_body.get('email')
        password = parsed_body.get('password')
        # get user info from database
        try:
            user = UserExtraInfo.objects.get(email=email)
        except UserExtraInfo.DoesNotExist:
            return JsonResponse({'success': False, 'message': 'User does not exist'})
        # check password
        if not user.check_password(password):
            return JsonResponse({'success': False, 'message': 'Invalid password'})
        user.backend = 'django.contrib.auth.backends.ModelBackend'
        login(request, user)
        return JsonResponse({'success': True, 'redirectUrl': 'https://' + request.get_host()+'/'})

securityscan/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView, View, FormView, UpdateView
from django.contrib.auth import logout
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from rest_framework.authtoken.models import Token

class BaseView( TemplateView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_logged_in'] = self.request.user.is_authenticated
        return context
    
class HomeView(BaseView):
    template_name = 'home.html'

class TargetView(BaseView):
    template_name = 'targets.html'

class ScanView(BaseView):
    template_name = 'scan.html'

class PricingView(BaseView):
    template_name = 'price.html'

class DashboardView(BaseView):
    template_name = 'dashboard.html'

class LoginView(TemplateView):
    template_name = 'login.html'

class SignupView(TemplateView):
    template_name = 'signup.html'

def google_logout(request):
    logout(request)
    return redirect('home')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charSet="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
    <title>{% block title %}Vulnerability scans, automated for any business{% endblock %}</title>
    <meta name="description"
        content="Online automated vulnerability scans for continuous monitoring of websites, servers, and applications. Test our free forever version." />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-toast-plugin/1.3.2/jquery.toast.min.css"
        integrity="sha512-wJgJNTBBkLit7ymC6vvzM1EcSWeM9mmOu+1USHaRBbHkm6W9EgM0HY27+UtUaprntaYQJF75rc8gjxllKs5OIQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'assests/static/css/tailwind.css' %}" data-n-g="" />
    <script src="https://code.jquery.com/jquery-3.6.0.js"
        integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-toast-plugin/1.3.2/jquery.toast.min.js"
        integrity="sha512-zlWWyZq71UMApAjih4WkaRpikgY9Bz1oXIW5G0fED4vk14JjGlQ1UmkGM392jEULP8jbNMiwLWdM8Z87Hu88Fw=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    {% block style %}{% endblock %}
</head>

</head>

<body>
    <div id="">
        {% block content %}
        {% endblock %}
    </div>
    <div class="hidden opacity-25 fixed inset-0 z-100 bg-black" id="modal_backdrop"></div>
</body>
<script>
    function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    function openModal(modalID) {
        $('header').toggleClass('z-50');
        $(`#${modalID}`).toggleClass('hidden')
        $(`#${modalID}`).toggleClass('flex')
        $('#modal_backdrop').toggleClass('hidden')
        $('#modal_backdrop').toggleClass('flex')
    }
    function showToastr(title, message, color) {
        $.toast({
            heading: title,
            text: message,
            position: 'top-right',
            stack: false,
            bgColor: color,
            textColor: 'white'
        })
    }
</script>
{% block script %}{% endblock %}

</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% include 'navbar.html' %}
<main class="flex grow flex-col justify-between">
    {% include 'intro_section.html' %}
    {% include 'leverage_section.html' %}
    {% include 'footer.html' %}
</main>
{% endblock %}

templates/intro_section.html
{% load static %}

<section class="bg-tiles-bottom relative max-w-full overflow-hidden pb-20 selection:bg-teal-100 md:pb-32">
    <div class="relative mx-auto max-w-7xl px-6 sm:px-8 md:px-12 z-10 mt-12 sm:mt-16 md:mt-20 lg:mt-24 xl:mt-32">
        <div class="flex">
            <div class="max-w-3xl text-left text-gray-800 ">
                <h1
                    class="mb-6 text-3xl font-bold text-gray-800 sm:text-4xl md:mb-8 md:text-4xl lg:text-5xl xl:text-6xl">
                    <span class="block">All in one</span> <span class="block whitespace-nowrap">Cyber Security
                    </span><span class="block"><span class="text-sky-700">Platform</span></span>
                </h1> <span class="text-sm md:text-base lg:text-lg">
                    <p class="mb-1 max-w-3xl">Conduct vulnerability and phishing assessments with OrionScan
                    </p>
                    <p class="max-w-3xl">Our mission is to increase security awareness around the world</p>
                </span>
            </div>
            <div class="relative hidden grow sm:block"><img alt="OrionScan Dashboard"
                    src="{% static 'screenshots/dashboard_2x.webp' %}" width="577" height="389" decoding="async" data-nimg="1"
                    class="max-w-24 block sm:-mt-0 sm:translate-x-4 lg:translate-x-16 xl:translate-x-14" loading="eager"
                    style="color:transparent" /></div>
        </div>
        <div class="relative mt-8 grow sm:hidden"><img alt="OrionScan Dashboard" src="{% static 'screenshots/dashboard_2x.webp' %}"
                width="577" height="389" decoding="async" data-nimg="1" class="w-full " loading="eager"
                style="color:transparent" /></div>
        <div class="xl:mt-30 relative z-10 mt-10 md:mt-16 md:px-0 lg:mt-20">
            <form>
                <label class="mb-3 block font-semibold text-slate-800 md:mb-4 md:text-xl">Try for free</label>
                <div class="relative">
                    <div aria-disabled="false"
                        class="flex h-12 grow rounded-xl border border-gray-400 bg-white pl-2 shadow-md shadow-sky-700/20 transition-all focus-within:border-sky-600 focus-within:shadow-lg focus-within:shadow-sky-600/20 aria-disabled:bg-slate-100 motion-reduce:transition-none sm:h-16 sm:text-lg md:h-20 md:pl-4 lg:text-2xl xl:text-3xl">
                        <input type="text" name="target"
                            class="grow border-none bg-transparent font-mono text-sm tracking-tighter focus:ring-0 disabled:text-slate-400 motion-reduce:transition-none sm:text-lg md:text-xl md:tracking-normal lg:text-2xl xl:text-3xl"
                            placeholder="Enter a URL, IP address or hostname" required="" autoCapitalize="none"
                            autoComplete="off" autoCorrect="off" value="" />
                        <button type="submit"
                            class="relative m-1 -ml-px hidden items-center rounded-xl border bg-sky-800 py-2 pl-8 pr-6 text-center font-bold text-white shadow-md transition-all hover:border-transparent hover:bg-black motion-reduce:transition-none sm:inline-flex md:text-xl">
                            Scan Now
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                                stroke="currentColor" aria-hidden="true" class="ml-4 inline-block h-8 w-8">
                                <path stroke-linecap="round" stroke-linejoin="round"
                                    d="M4.5 12h15m0 0l-6.75-6.75M19.5 12l-6.75 6.75"></path>
                            </svg>
                        </button>
                    </div>
                </div>
                <button type="submit"
                    class="mr-lg relative mt-4 block w-full rounded-lg border-black bg-sky-800 px-10 py-3 font-bold text-white shadow-md hover:bg-slate-900 sm:hidden">
                    Scan Now
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                        stroke="currentColor" aria-hidden="true" class="inline-block h-6 w-6">
                        <path stroke-linecap="round" stroke-linejoin="round"
                            d="M4.5 12h15m0 0l-6.75-6.75M19.5 12l-6.75 6.75"> </path>
                    </svg>
                </button>
            </form>
        </div>
    </div>
</section>

templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %} OrionScan | Login {% endblock %}
{% block script %}
    <script src="{% static 'assests/static/js/login.js' %}"></script>
{% endblock %}

{% block content %}
{% include 'navbar.html' %}

<main class="flex grow flex-col justify-between">
    <div class="bg-white">
        {% include 'login_content.html' %}
        {% include 'footer.html' %}
    </div>
</main>
<script>
    loginUrl = "{% url 'signup:loginWithEmail' %}"
</script>

{% endblock %}

templates/navbar.html
{% load static %}

<header class="sticky top-0 z-50 border-b border-gray-200 bg-white">
    <nav class="pr relative z-10 mx-auto flex max-w-7xl items-center py-4 px-6 transition-all motion-reduce:transition-none sm:px-8 md:px-12 lg:py-4"
        aria-label="Global">
        <div class="">
            <a class="navbar-brand" href="{% url 'home' %}"> <img src="{% static 'images/logo.png' %}"
                    alt="OrionScanLogo" width="250px" srcset=""> </a>
        </div>
        <div class="grow"> </div>
        <div class="hidden sm:flex lg:space-x-4">
            <a class="border-b-2 border-transparent p-2 text-sm font-medium transition-all hover:border-b-black motion-reduce:transition-none lg:px-4 lg:text-base"
                href="{% url 'targets' %}">Targets</a>
            <a class="border-b-2 border-transparent p-2 text-sm font-medium transition-all hover:border-b-black motion-reduce:transition-none lg:px-4 lg:text-base"
                href="{% url 'scan' %}">Scanners</a>
            <a class="border-b-2 border-transparent p-2 text-sm font-medium transition-all hover:border-b-black motion-reduce:transition-none lg:px-4 lg:text-base"
                href="{% url 'pricing' %}">Pricing</a>
            <a class="border-b-2 border-transparent p-2 text-sm font-medium transition-all hover:border-b-black motion-reduce:transition-none lg:px-4 lg:text-base"
                href="{% url 'dashboard' %}">Dashboard
            </a>
        </div>
        {% if is_logged_in %}
        <a class="mr-2 hidden border-b-2 border-transparent p-2 text-sm font-medium transition-all hover:border-b-black hover:bg-white hover:opacity-100 motion-reduce:transition-none sm:block lg:mr-4 lg:px-4 lg:text-base"
            href="{% url 'logout' %}" >{{ request.user.username }}</a>
        {% else %}
        <a class="mr-2 hidden border-b-2 border-transparent p-2 text-sm font-medium transition-all hover:border-b-black hover:bg-white hover:opacity-100 motion-reduce:transition-none sm:block lg:mr-4 lg:px-4 lg:text-base"
            href="{% url 'login' %}">Log In</a><a
            class="inline-flex items-center rounded-md border border-gray-200 bg-white px-2 py-2 text-xs font-medium transition-all hover:border-black hover:opacity-100 focus:outline-none focus:ring-offset-2 motion-reduce:transition-none md:px-4 md:py-2 md:text-base"
            href="{% url 'signup' %}">Sign Up</a>
        {% endif %}
        <div data-headlessui-state="">
            <button
                class="relative z-10 ml-2 -mr-2 flex h-8 w-8 items-center justify-center sm:hidden [&amp;:not(:focus-visible)]:focus:outline-none"
                aria-label="Toggle Navigation" type="button" aria-expanded="false" data-headlessui-state="">
                <svg aria-hidden="true" class="h-3.5 w-3.5 overflow-visible stroke-gray-800" fill="none"
                    stroke-width="2" stroke-linecap="round">
                    <path d="M0 1H14M0 7H14M0 13H14" class="origin-center transition"></path>
                    <path d="M2 2L12 12M12 2L2 12" class="origin-center transition scale-90 opacity-0"></path>
                </svg>
            </button>
        </div>
    </nav>
</header>

templates/price.html
{% extends 'base.html' %}
{% load static %}

{% block title %} OrionScan | Pricing {% endblock %}

{% block content %}
{% include 'navbar.html' %}

<main class="flex grow flex-col justify-between">
    <div class="bg-white">
        {% include 'price_plan.html' %}
        {% include 'price_frequent_section.html' %}
        {% include 'footer.html' %}
    </div>
</main>

{% endblock %}

templates/scan.html
{% extends 'base.html' %}
{% load static %}

{% block title %} OrionScan | Scan {% endblock %}
{% block style %}
<link rel="stylesheet" href="{% static 'assests/static/css/style.css' %}" data-n-g="" />
{% endblock %}

{% block content %}
{% include 'navbar.html' %}
<div class="flex flex-col w-full h-full grow">
    {% include 'scan_content.html' %}
    <footer class="text-xs opacity-50 text-center mt-16 py-4">© OrionScan, LLC. 2019 - 2023. All Rights Reserved | <a
            href="#">Terms &amp; Policies</a></footer>
</div>
{% endblock %}

templates/scan_content.html
{% load static %}

<main class="grow flex flex-col">
    <div class="px-2 sm:px-6 grow">
        <div class="flex items-center pl-4">
            <h1>Scans</h1>
            <div class="flex items-end justify-end py-2">
                <button class="border border-sky-600 text-sky-700 shadow shadow-slate-300 bg-white hover:bg-sky-100 hover:text-sky-600 block rounded-md py-2 px-4 mx-2 text-sm">Add Targets</button>
                <button class="border border-sky-700 bg-sky-600 hover:bg-sky-500 text-white text-sm sm:text-base shadow shadow-slate-300 font-bold block rounded-md py-2 px-4 ml sm:ml-2 sm:mt-0 whitespace-nowrap">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true" class="h-4 sm:h-6 inline-block mr-2">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v6m3-3H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                    </svg>New Scan</button>
            </div>
        </div>
        <div class="bg-white rounded-md shadow-md p-6">
            <div class="grid grid-cols-2">
                <div class="grow"></div>
                <div class="flex justify-end md:col-span-2 lg:col-span-2 xl:col-span-1">
                    <button class="border border-slate-400 hover:bg-sky-50 hover:text-sky-700 px-4 py-2 rounded-md shadow shadow-sky-100 focus:border-sky-600 focus:ring-sky-600 focus:ring-1 text-slate-700 text-sm font-medium whitespace-nowrap transition-all motion-reduce:transition-none" title="Filter scans"><span><svg xmlns="http://www.w3.org/2000/svg" fill="none"
                                viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor"
                                aria-hidden="true" class="w-4 h-4 inline-block">
                                <path stroke-linecap="round" stroke-linejoin="round"
                                    d="M10.5 6h9.75M10.5 6a1.5 1.5 0 11-3 0m3 0a1.5 1.5 0 10-3 0M3.75 6H7.5m3 12h9.75m-9.75 0a1.5 1.5 0 01-3 0m3 0a1.5 1.5 0 00-3 0m-3.75 0H7.5m9-6h3.75m-3.75 0a1.5 1.5 0 01-3 0m3 0a1.5 1.5 0 00-3 0m-9.75 0h9.75">
                                </path>
                            </svg> Filters </span></button>
                </div>
                <div class="basis-full h-0 col-span-full"></div>
            </div>
            <div class="mt-4">
                <div class="border-2 border-slate-200 border-dashed h-full w-full rounded p-8 flex justify-center items-center">
                    <p class="text-sm text-slate-400 font-medium">No data to display</p>
                </div>
            </div>
        </div>
    </div>
</main>

templates/signup.html
{% extends 'base.html' %}
{% load static %}

{% block title %} OrionScan | Signup {% endblock %}
{% block script %}
<script src="{% static 'assests/static/js/signup.js' %}"></script>
{% endblock %}

{% block content %}
{% include 'navbar.html' %}

<main class="flex grow flex-col justify-between">
    <div class="bg-white">
        <!-- if token param exists -->
        {% if token %}
        {% include 'signup_with_token.html' %}
        {% else %}
        {% include 'signup_content.html' %}
        {% endif %}
        {% include 'footer.html' %}
    </div>
</main>

<script>
    sendMailUrl = "{% url 'signup:signupWithEmail' %}"
    signupUrl = "{% url 'signup:signupWithToken' %}"
</script>

{% endblock %}

templates/targets.html
{% extends 'base.html' %}
{% load static %}

{% block title %} OrionScan | Targets {% endblock %}
{% block style %}
<link rel="stylesheet" href="{% static 'assests/static/css/style.css' %}" data-n-g="" />
{% endblock %}

{% block content %}
{% include 'navbar.html' %}
<div class="flex flex-col w-full h-full grow">
    {% include 'targets_content.html' %}
    <footer class="text-xs opacity-50 text-center mt-16 py-4">© OrionScan, LLC. 2019 - 2023. All Rights Reserved | <a
            href="#">Terms &amp; Policies</a></footer>
</div>
{% endblock %}

{% block script %}
<script>
    scanUrl = "{% url 'dashboard:scan' %}"
</script>
<script src="{% static 'assests/static/js/scan.js' %}"></script>
<script type="text/babel">
    const AddTargetButton = () => {
        const [open, setOpen] = React.useState(false);
        const { Button, Dialog, DialogActions, DialogContent, DialogContentText, DialogTitle, Grid, Divider } = MaterialUI;
        const [target, setTarget] = React.useState('');
        const [tags, setTags] = React.useState('');
        const [label, setLabels] = React.useState('');

        const handleClickOpen = () => {
            setOpen(true);
        };

        const handleClose = () => {
            setOpen(false);
            setTarget('');
            setTags('');
            setLabels('');
        };

        return (
            <div>
                <button onClick={handleClickOpen}
                    className="border border-sky-600 text-sky-700 shadow shadow-slate-300 bg-white hover:bg-sky-100 hover:text-sky-600 block rounded-md py-2 px-4 mx-2 text-sm">Add
                    Targets</button>
                <Dialog
                    open={open}
                    onClose={handleClose}
                    maxWidth='lg'
                    aria-labelledby="alert-dialog-title"
                    aria-describedby="alert-dialog-description"
                >
                    <DialogTitle id="alert-dialog-title">{"Add Targets"}</DialogTitle>
                    <DialogContent>
                        <DialogContentText id="alert-dialog-description">
                            Add targets individually by IP, DNS Name, or URL. Once created, you can configure advanced options for each target.
                        </DialogContentText>
                        <div className="pb-6 sm:pb-3 mb-6 sm:mb-3 border-b border-slate-200">
                            <div className="grid grid-cols-1 sm:grid-cols-12 gap-4">
                                <div className="sm:col-span-5">
                                    <label>Target *</label>
                                    <input className="block w-full rounded-md border border-slate-300 shadow-sm h-14 px-4 py-5 default-input-style peer" type="text" data-lpignore="true" placeholder="IPv4, Domain, URL or Public CIDR" tabIndex="0"
                                        id='scan_target' onChange={(e) => setTarget(e.target.value)} />
                                    <div className="hidden peer-[&amp;:not(:placeholder-shown):not(:focus):invalid]:block text-red-500 text-xs mt-1">Invalid IPv4, Fully Qualified Domain Name, URL or Public CIDR(&gt;19)</div>
                                </div>
                                <div className='sm:col-span-3'><label>Tags</label>
                                    <input className="block w-full rounded-md border border-slate-300 shadow-sm h-14 px-4 py-5 default-input-style peer" type="text" data-lpignore="true" placeholder="Up to 5 tags" tabIndex="0"
                                        onChange={(e) => setTags(e.target.value)} />
                                </div>
                                <div className="sm:col-span-4"><label>Label</label>
                                    <input type="text" data-lpignore="true" placeholder="e.g. my-example-server"
                                        onChange={(e) => setLabels(e.target.value)} /></div>
                            </div>
                        </div>
                        <div className="pb-6 sm:pb-3 mb-6 sm:mb-3 border-b border-slate-200">
                            <div className="grid grid-cols-1 sm:grid-cols-12 gap-4">
                                <div className="sm:col-span-5">
                                    <label>Target *</label>
                                    <input className="block w-full rounded-md border border-slate-300 shadow-sm h-14 px-4 py-5 default-input-style peer" type="text" data-lpignore="true" placeholder="IPv4, Domain, URL or Public CIDR" tabIndex="0" />
                                    <div className="hidden peer-[&amp;:not(:placeholder-shown):not(:focus):invalid]:block text-red-500 text-xs mt-1">Invalid IPv4, Fully Qualified Domain Name, URL or Public CIDR(&gt;19)</div>
                                </div>
                                <div className='sm:col-span-3'><label>Tags</label>
                                    <input className="block w-full rounded-md border border-slate-300 shadow-sm h-14 px-4 py-5 default-input-style peer" type="text" data-lpignore="true" placeholder="Up to 5 tags" tabIndex="0" />
                                </div>
                                <div className="sm:col-span-4"><label>Label</label>
                                    <input type="text" data-lpignore="true" placeholder="e.g. my-example-server" /></div>
                            </div>
                        </div>
                        <DialogActions>
                            <Button id='scan_button' variant='contained' color="primary" disabled={!target}>
                                Submit
                            </Button>
                        </DialogActions>
                    </DialogContent>
                </Dialog>
            </div>
        );
    }

</script>
{% endblock %}